server: DHCPserver
	./DHCPserver 5000

DHCPserver: DHCPserver.cpp
	g++ -o DHCPserver DHCPserver.cpp

client: DHCPclient
	./DHCPclient 5000

DHCPclient: DHCPclient.cpp
	g++ -o DHCPclient DHCPclient.cpp
